# Я художник, я так вижу, визуализация данных в питоне

# I. Numpy

### Импортируйте NumPy

In [1]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [2]:
ary = np.zeros(10)
ary[4] = 1
ary_5_2 = ary.reshape(5, 2)
print(ary_5_2)
ary_2_5 = ary.reshape(2, 5)
print(ary_2_5)

[[0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [3]:
ary = np.arange(10, 50)
print(ary)
ary_reversed = ary[::-1]
print(ary_reversed)
even_elements = ary[ary % 2 == 0]
even_elements

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [4]:
ary_3_3 = np.arange(9).reshape(3, 3)
ary_3_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [5]:
ary_4_3_2 = np.random.rand(4, 3, 2)
print(ary_4_3_2)
print("Минимальное значение:", round(np.min(ary_4_3_2), 8))
print("Максимальное значение:", round(np.max(ary_4_3_2), 8))

[[[0.85257232 0.9225125 ]
  [0.17714829 0.50490449]
  [0.82010829 0.42604474]]

 [[0.93120491 0.31300897]
  [0.5767859  0.83155091]
  [0.387653   0.85833014]]

 [[0.3788748  0.4235568 ]
  [0.43620218 0.68273842]
  [0.07631973 0.05619387]]

 [[0.61988881 0.44774509]
  [0.42409432 0.80167689]
  [0.06041107 0.96770344]]]
Минимальное значение: 0.05619387
Максимальное значение: 0.96770344


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [6]:
ary_6_4 = np.random.rand(6, 4)
ary_4_3 = np.random.rand(4, 3)
print(ary_6_4)
print(ary_4_3)
multiplicated_matrix = np.dot(ary_6_4, ary_4_3)
multiplicated_matrix

[[0.7892405  0.80256014 0.27623105 0.22468527]
 [0.29249618 0.92796508 0.16946516 0.0503265 ]
 [0.01596034 0.65387718 0.34181001 0.19535108]
 [0.58937418 0.93397578 0.42790456 0.70873978]
 [0.87200744 0.54832679 0.27783739 0.25146031]
 [0.89947616 0.36972446 0.56512003 0.70384602]]
[[0.42720208 0.35546238 0.48210345]
 [0.72713391 0.7052147  0.87171994]
 [0.02617356 0.15412627 0.15552751]
 [0.99441786 0.49838052 0.34108188]]


array([[1.15139487, 1.00107573, 1.19970083],
       [0.85419093, 0.80958679, 0.99346103],
       [0.68548155, 0.61683818, 0.69748388],
       [1.64689061, 1.28732723, 1.40659385],
       [1.02855901, 0.86479891, 1.02736509],
       [1.36780555, 1.01834805, 1.08389758]])

### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [7]:
ary_7_7 = np.random.randint(0, 10, size=(100, 100))
print(ary_7_7)

mean = np.mean(ary_7_7)
std = np.std(ary_7_7)
print("Среднее значение:", round(mean,4))
print("Стандартное отклонение:", round(std,4))

normalized_ary = (ary_7_7 - ary_7_7.min()) / (ary_7_7.max() - ary_7_7.min())
print("Нормализованный массив:")
print(normalized_ary.round(2))

[[6 0 3 ... 9 5 9]
 [2 5 0 ... 2 0 0]
 [8 2 8 ... 8 2 7]
 ...
 [1 3 5 ... 8 8 4]
 [2 2 9 ... 3 2 5]
 [5 9 4 ... 9 2 5]]
Среднее значение: 4.5142
Стандартное отклонение: 2.8958
Нормализованный массив:
[[0.67 0.   0.33 ... 1.   0.56 1.  ]
 [0.22 0.56 0.   ... 0.22 0.   0.  ]
 [0.89 0.22 0.89 ... 0.89 0.22 0.78]
 ...
 [0.11 0.33 0.56 ... 0.89 0.89 0.44]
 [0.22 0.22 1.   ... 0.33 0.22 0.56]
 [0.56 1.   0.44 ... 1.   0.22 0.56]]


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Загрузите датасет Tips из набора датасетов seaborn

In [9]:
tips = sns.load_dataset('tips')

### Посмотрите на первые 5 строчек

In [10]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Узнайте сколько всего строчек и колонок в данных

In [11]:
tips.shape

(244, 7)

### Проверьте есть ли пропуски в данных

In [12]:
tips.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

### Посмотрите на распределение числовых признаков

In [13]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

### Найдите максимальное значение 'total_bill'

In [14]:
tips['total_bill'].max()

50.81

### Найдите количество курящих людей

In [15]:
print("Число курящих:", tips[tips['smoker'] == 'Yes'].shape[0])

Число курящих: 93


### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [16]:
tips.groupby('day')['total_bill'].mean().round(1)

C:\Users\sergey.makarov\AppData\Local\Temp\ipykernel_21588\1184127371.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby('day')['total_bill'].mean().round(1)


day
Thur    17.7
Fri     17.2
Sat     20.4
Sun     21.4
Name: total_bill, dtype: float64

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [17]:
median_bill = tips['total_bill'].median()
overmedianed_tips = tips[tips['total_bill'] > median_bill]
overmedianed_tips.groupby('sex')['tip'].mean().round(1)

C:\Users\sergey.makarov\AppData\Local\Temp\ipykernel_21588\3727327551.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  overmedianed_tips.groupby('sex')['tip'].mean().round(1)


sex
Male      3.8
Female    3.7
Name: tip, dtype: float64

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [18]:
tips['smoker_binary'] = tips['smoker'].map({'No': 0, 'Yes': 1})
tips[['smoker', 'smoker_binary']].head(3)

smoker smoker_binary
0     No             0
1     No             0
2     No             0

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

In [19]:
# ВАШ КОД ЗДЕСЬ

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

In [20]:
# ВАШ КОД ЗДЕСЬ

### Постройте pairplot

In [21]:
# ВАШ КОД ЗДЕСЬ

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

In [22]:
# ВАШ КОД ЗДЕСЬ

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

In [23]:
# ВАШ КОД ЗДЕСЬ

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

In [24]:
# ВАШ КОД ЗДЕСЬ

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.

In [25]:
# ВАШ КОД ЗДЕСЬ