# “Git push -f” или после нас хоть потоп

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных.

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией.
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

 С этими библиотеками вы будете знакомится дальше на курсе, а пока давайте попрактикуемся в решении базовых задач на  чистом Python.

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [4]:
def share_bread(N, K):
    x = K // N      # Количество кусков, которое достанется каждому хоббиту
    y = K % N       # Количество кусков, которое останется в корзине
    return x, y
         # если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

x, y = share_bread(N=3, K=14)
print(f"Хоббитам достанется по {x} куска хлеба, в корзине останется {y} куска.")

Хоббитам достанется по 4 куска хлеба, в корзине останется 2 куска.


## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [9]:
def leap_year(year):
    if (year % 400 == 0) or ((year % 100 != 0) and (year % 4 == 0)) : return "YOU SHALL PASS"
    else: return "YOU SHALL NOT PASS"
          # если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert leap_year(5) == 'YOU SHALL NOT PASS'

print("1900 ->", leap_year(1900))       # YOU SHALL NOT PASS (кратен 100, но не 400)


1900 -> YOU SHALL NOT PASS


## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>


Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

**Подсказка:** используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [19]:
def amulet_area(a, b, c):
          # Проверка возможности существования треугольника с заданными длинами сторон
    if a + b <= c or a + c <= b or b + c <= a: return "Треугольника с указанными сторонами не существует!"
          # Расчет полупериметра
    half_perimetr = (a + b + c) / 2
          # Возврат площади, вычисленной по формуле Герона
    return (half_perimetr * (half_perimetr - a) * (half_perimetr - b) * (half_perimetr - c))**0.5

print(amulet_area(1, 1, 3))   # Треугольника не существует

assert amulet_area(3, 4, 5) == 6
print("Треугольник со сторонами 3, 4 и 5 имеет площадь:", amulet_area(3, 4, 5))

Треугольника с указанными сторонами не существует!
Треугольник со сторонами 3, 4 и 5 имеет площадь: 6.0


## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - написать функцию под каждую из них. Важное условие - используйте только базовые функции для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [36]:
def cal_euclidean(a, b):
          # Расчет Евклидова расстояния между точками с заданными координатами
    distance = 0
    for i in range(len(a)-1): distance += round(((a[i] - a[i+1])**2 + (b[i] - b[i+1])**2) **0.5, 2)
    return distance

def cal_manhattan(a, b):
          # Расчет расстояния между точками с заданными координатами по методу Манхэттена
    distance = 0
    for i in range(len(a)-1): distance += (abs(a[i] - a[i+1]) + abs(b[i] - b[i+1]))
    return distance

def cal_cosine(a, b):
          # Расчет косинусного расстояния между векторами с заданными параметрами
    distance = 1
    multiplication = 0
    vector_a = 0
    vector_b = 0
    for ai, bi in zip(a, b):  # Подготовка сумм и произведения на основе данных векторов
        multiplication += abs(ai * bi)
        vector_a += ai**2
        vector_b += bi**2
          # Расчет косинусного расстояния
    if ((vector_a != 0) and (vector_a != 0)) :
        distance = round(1 - multiplication / (vector_a**0.5 * vector_b**0.5), 2)
    else: return 1           # Возврат единицы, если имеется нулевой вектор
    return distance

In [38]:
          # Подключение библиотеки
import numpy as np

a = np.random.randint(-10, 10, size=3)
b = np.random.randint(-10, 10, size=3)

print("Расстояние между точками:")
for ai, bi in zip(a, b) :
    print("({0}, {1})".format(ai, bi))
print("по Евклидовому методу:", round(cal_euclidean(a, b), 2), ";")
print("по методу Манхеттена:", cal_manhattan(a, b), ".")
print("\nКосинусное расстояние между векторами:")
print(a)
print(b)
print("составляет:", cal_cosine(a, b), ".")

Расстояние между точками:
(-9, -9)
(8, -6)
(8, 5)
по Евклидовому методу: 28.26 ;
по методу Манхеттена: 31 .

Косинусное расстояние между векторами:
[-9  8  8]
[-9 -6  5]
составляет: 0.02 .


## Задача 5* (бонусное неоцениваемое задание)

**Замечание:** Поскольку библиотеку numpy мы будем подробно разбирать дальше, то это задание является бонусным, его выполнение необязательно для сдачи ДЗ и не влияет на итоговый балл. Как вариант, можете вернуться к нему после прохождения numpy ;)



Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в интервале от 0 до 1 остаются прежними

In [45]:
          # Подключение библиотеки
import numpy as np
          # Создание массива из 100 элементов
my_array = np.random.rand(100)

print("Исходный массив:")
print(my_array)
print("Максимальное значение:", np.max(my_array))
print("Минимальное значение:", np.min(my_array))
          # Преобразование массива (максимальный элемент - 1, минимальный элемент - 0)
my_array_min_max = (my_array - np.min(my_array)) / (np.max(my_array) - np.min(my_array))
print("Преобразованный массив:")
print(my_array_min_max)

Исходный массив:
[0.11032543 0.17918723 0.53477135 0.14778852 0.51080332 0.06989551
 0.09649384 0.74713984 0.55511024 0.21425454 0.13574986 0.29491979
 0.23056598 0.30871112 0.67080555 0.64936908 0.38644564 0.33984092
 0.61968221 0.87989631 0.51123277 0.31820914 0.45834359 0.82226484
 0.68937722 0.07035037 0.19899201 0.38103499 0.68733248 0.16563699
 0.96630718 0.67450087 0.15646833 0.94369098 0.61029939 0.39170295
 0.2578418  0.55297853 0.06470462 0.88059288 0.35431981 0.71266389
 0.99251761 0.95124399 0.19168854 0.07818168 0.12096342 0.16499695
 0.16988744 0.90350757 0.81641423 0.11282851 0.26172585 0.91593659
 0.13651307 0.47874322 0.90179991 0.8366353  0.25113075 0.66690575
 0.12753707 0.31917202 0.85611617 0.6807219  0.59481915 0.82136834
 0.08669998 0.32220887 0.65634844 0.98271604 0.58439637 0.00610668
 0.06571119 0.38603866 0.57082064 0.83967507 0.91636417 0.25499084
 0.12359264 0.44026491 0.25115292 0.48468234 0.67987981 0.07803815
 0.57095721 0.51208015 0.76779268 0.70234541 

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы

In [52]:
          # Подключение библиотеки
import numpy as np
          # Создание массива 5 х 6 со случайными целыми числами от 0 до 50
my_array = np.random.randint(0, 51, size=(5, 6))
          # Поиск индекса колонки с максимальным элементом
max_col_index = np.argmax(np.max(my_array, axis=0))
          # Выбор колонки по найденному индексу
selected_column = my_array[:, max_col_index]

print("Размерность (Shape): ", my_array.shape)
print("Массив (Array) :")
print(my_array)
print("Столбец с максимальным элементом (", np.max(my_array), "):")
for i in range(len(selected_column)) : print(selected_column[i])

Размерность (Shape):  (5, 6)
Массив (Array) :
[[31 24 38 38 10 30]
 [39 45  3 34 23 20]
 [ 4 39 29 35 29 49]
 [ 2  9 11 47 50 22]
 [33  8 26 30 43  2]]
Столбец с максимальным элементом ( 50 ):
10
23
29
50
43


Напишите функцию, которая принимает на вход матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [85]:
def get_unique_rows(X):
          # Отбор индексов уникальных строк
    tuples = [tuple(row) for row in X]
    _, unique_indices = np.unique(tuples, axis=0, return_index=True)
          # Упорядочивание списка индексов уникальных строк
    X_unique = X[sorted(unique_indices)]
    return X_unique

In [89]:
X = np.random.randint(4, 6, size=(7,3))
print(X)

[[5 4 5]
 [5 4 4]
 [5 5 5]
 [5 4 5]
 [5 4 5]
 [5 5 4]
 [5 5 5]]


In [88]:
          # Вывод результатов
print("Исходная матрица:")
print(X)
unique_X = get_unique_rows(X)
print("Уникальные строки:")
print(unique_X)

Исходная матрица:
[[4 4 4]
 [5 4 4]
 [5 4 5]
 [5 4 4]
 [5 4 4]
 [4 5 5]]
Уникальные строки:
[[4 4 4]
 [5 4 4]
 [5 4 5]
 [4 5 5]]
